spring:
  liquibase:
    change-log: classpath:db/changelog/table.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/mini-mail
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

